pipeline {
    agent any
    stages {
        stage('Example') {
            environment { 
                DEBUG_FLAGS = '-g'
            }
            steps {
                sh 'env | sort'
                sh 'ls -al'
            }
        }
    }
}
